import os
from google.adk.agents import Agent

MODEL = os.getenv("ADK_MODEL", "gemini-2.0-flash")

def evaluate_analysis_governance(analysis_result: str, prompt: str) -> dict:
    """
    Evaluates the analysis result against the original prompt and strict data governance rules.
    Checks for logical soundness and temporal disjoints (e.g., correlating 2020-2021 customer data with 2025 revenue).
    
    Args:
        analysis_result: The insights generated by the Stats Agent.
        prompt: The original user request.
        
    Returns:
        A dictionary indicating if the analysis is approved, along with feedback.
    """
    approved = True
    feedback = "Analysis satisfies all governance rules."
    
    # Simple heuristic to detect temporal violations
    lower_analysis = str(analysis_result).lower()
    lower_prompt = str(prompt).lower()
    
    # If the user tries to correlate or join customer demographic data with 2025 transaction data
    if "correlate" in lower_prompt or "impact" in lower_prompt or "join" in lower_prompt:
        if ("2020" in lower_analysis or "2021" in lower_analysis) and "2025" in lower_analysis:
            approved = False
            feedback = (
                "GOVERNANCE REJECTION: Detected logical temporal disjoint. "
                "Attempting to correlate customer acquisition from 2020-2021 "
                "with transaction data from 2025 without intermediate bridge data is statistically invalid."
            )
            
    return {
        "approved": approved,
        "feedback": feedback
    }

critic_instruction = """
You are the Critic Agent, the Automated QA Evaluator.
Your role is to intercept the output from the Statistical Agent and ensure it is logically sound and adheres to data governance.

The datasets span two disparate timeframes:
- Transactions (`sample.csv`): 2025
- Customers (`customers-1000.csv`): 2020-2021

These must be analyzed as independent streams. They cannot be temporally joined.
Use the `evaluate_analysis_governance` tool to validate the Stats Agent's output against the user's prompt.
If the tool returns approved=False, you MUST explain the governance violation to the user.
If it is approved, simply forward the insights.
"""

critic_agent = Agent(
    model=MODEL,
    name="critic_agent",
    instruction=critic_instruction,
    tools=[evaluate_analysis_governance]
)
